[package]
name = "rustyscraper"
version = "0.0.1"
authors = [ "rob thijssen <rthijssen@gmail.com>" ]

[dependencies]
chrono = "^0.4"
glob = "^0.3"
reqwest = "^0.9"
select = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_yaml = "^0.8"